name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: pull_request
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - id: magic
        run: sudo apt-get install -y imagemagick
      - id: gen_table
      - run: |
          echo "table=$(ls -la)" >> "$GITHUB_OUTPUT"

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Hello world ${{ steps.gen_table.outputs.table }} ! :wave:

